# Generated by Django 3.1.13 on 2021-08-22 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_auto_20210821_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doc_parent', to='documents.document'),
        ),
        migrations.AlterField(
            model_name='document',
            name='childs',
            field=models.ManyToManyField(related_name='doc_childs', to='documents.Document'),
        ),
    ]
