# Generated by Django 3.1.13 on 2021-08-22 17:33

from django.db import migrations, models
import software_challenge_api.documents.models.documents


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_auto_20210822_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=software_challenge_api.documents.models.documents.get_upload_path),
        ),
    ]
