# Generated by Django 3.1.13 on 2021-08-22 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_auto_20210822_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='childs',
            field=models.ManyToManyField(blank=True, null=True, related_name='doc_childs', to='documents.Document'),
        ),
    ]
